---
- name: Deploy Ansible development server
  hosts: fedora
  become: true

  vars:
    ### vars in <server_config.yml> ###
    # registry_user:  username for private automation hub for EE or to password protected registry
    # registry_pass: password for private automation hub for EE or to password protected registry 
    # username: password for private automation hub for EE or to password protected registry 
    # dev_server_password: dev server password (optional)
    # dev_server_port: port for web server access
    # ansible_image: specific image to pull to development server and assign in ansible-navigator.yml
    ### end of <server_config.yml> ###

    # Deploy an inventory, group variables and host variables files from files folder in role
    deploy_inventory: true
    # Deploy an example repository with a basic role structure
    deploy_example_repo: true
    # Deploy an example repository using ansible-galaxy init
    deploy_ansiblegalaxy_repo: false

    # ssl
    configure_ssl: true
    cert_dir: "{{ playbook_dir }}/ssl"
    cert_dir_dest: /etc/pki/tls/certs
    cert_name: "fullchain_{{ username }}.code.autodotes.com.crt"
    key_name: "{{ username }}.code.autodotes.com.key"

  vars_files:
    - server_config.yml

  roles:
    - shadowman_dev_server
